/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Cities', [
      {
        name: 'Анталия',
        country_id: 1,
        zip_code: 7170,
        population: 945049,
        rating: 4.35,
        internet: '7 MBPs',
        best_nbh: 'Район Коньяалты',
        photo: 'https://horosho-tam.ru/thumb/top/pics/9a/13/59a8507c0b3ec54050d9139a/antaliya.jpg',
        video_url: 'https://www.youtube.com/watch?v=6QEp58Cu98M&ab_channel=RashimilianTravel',
        map_screen: 'https://nomadlist.com/assets/img/static-maps/antalya-turkey.png?1655251594',
        map_url: 'https://www.google.com/maps/@36.88414,30.70563,13z',
        nbhs_map: 'https://hoodmaps.com/antalya-neighborhood-map',
        quality_of_life: '3',
        family_score: '3',
        safety: '4',
        english_speaking: '2',
        nightlife: '4',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Тбилиси',
        country_id: 2,
        zip_code: 0162,
        population: 3728600,
        rating: 4.2,
        internet: '10 MBPs',
        best_nbh: 'Старый город, Мтацминда',
        upcoming_nbh: 'Зейтинкей',
        photo: 'https://kartinkin.net/uploads/posts/2022-02/1645860795_40-kartinkin-net-p-gruziya-kartinki-47.jpg',
        video_url: 'https://www.youtube.com/watch?v=1CE6W5BubQo&list=WL&index=1&t=11s&ab_channel=Chady',
        map_screen: 'https://nomadlist.com/assets/img/static-maps/tbilisi-georgia.png?1653004840',
        map_url: 'https://www.google.com/maps/@41.716667,44.783333,13z',
        nbhs_map: 'https://hoodmaps.com/tbilisi-neighborhood-map',
        quality_of_life: '4',
        family_score: '3',
        safety: '4',
        english_speaking: '2',
        nightlife: '2',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Констанца',
        country_id: 3,
        zip_code: 900178,
        population: 280000,
        rating: 3.2,
        internet: '27 MBPs',
        best_nbh: 'Фалеза Норд Трокадеро',
        photo: 'https://www.orangesmile.com/common/img_cities_original/constanta--1156502-3.jpg',
        video_url: 'https://www.youtube.com/watch?v=CAd845EiMCo&ab_channel=DabbleandTravel',
        map_screen: 'https://nomadlist.com/assets/img/static-maps/constanta-romania.png?1641513741',
        map_url: 'https://goo.gl/maps/TnYe3G39jzes8RYf9',
        nbhs_map: 'https://hoodmaps.com/constanta-neighborhood-map',
        quality_of_life: '4',
        family_score: '3',
        safety: '4',
        english_speaking: '3',
        nightlife: '3',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Будапешт',
        country_id: 4,
        zip_code: 1028,
        population: 1800000,
        rating: 3.52,
        internet: '30 MBPs',
        best_nbh: 'Бельварош-Липотварош, Терезварош',
        upcoming_nbh: 'Йожефварош',
        photo: 'https://wallscloud.net/img/resize/1024/768/MM/2018-06-22-uFCP5FcUq7Y.jpg',
        video_url: 'https://youtu.be/5ynGpsRtNHw',
        map_screen: 'https://nomadlist.com/assets/img/static-maps/budapest-hungary.png?1641513677',
        map_url: 'https://goo.gl/maps/eSP2BP5Ef7eXhD3t5',
        nbhs_map: 'https://hoodmaps.com/budapest-neighborhood-map',
        quality_of_life: '4',
        family_score: '3',
        safety: '4',
        english_speaking: '3',
        nightlife: '4',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Лос Анджелес',
        country_id: 5,
        zip_code: 90010,
        population: 3884307,
        rating: 2.92,
        internet: '52 MBPs',
        best_nbh: 'Даунтаун',
        upcoming_nbh: 'Скид Роу',
        photo: 'https://wallscloud.net/img/resize/1024/768/MM/2018-08-08-palmy_rassvet_ptitsy_125099_1920x1080.jpg',
        video_url: 'https://youtu.be/bTvr_2v-0HI',
        map_screen: 'https://nomadlist.com/assets/img/static-maps/los-angeles-ca-united-states.png?1647820873',
        map_url: 'https://goo.gl/maps/XbDzbpy65MZPsbeUA',
        nbhs_map: 'https://hoodmaps.com/los-angeles-neighborhood-map',
        quality_of_life: '4',
        family_score: '4',
        safety: '3',
        english_speaking: '5',
        nightlife: '5',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Мадейра',
        country_id: 6,
        zip_code: 9020,
        population: 253945,
        rating: 3.76,
        internet: '32 MBPs',
        best_nbh: 'Porto Santo',
        photo: 'https://www.cruiz.info/ship-sea/exc/985_2.jpg',
        video_url: 'https://youtu.be/-rdGyeFGWXY',
        map_screen: 'https://nomadlist.com/assets/img/static-maps/madeira-portugal.png?1661472042',
        map_url: 'https://goo.gl/maps/4v5VvcgoH8G8UUvH9',
        nbhs_map: 'https://hoodmaps.com/madeira-neighborhood-map',
        quality_of_life: '4',
        family_score: '4',
        safety: '5',
        english_speaking: '4',
        nightlife: '3',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Мельбурн',
        country_id: 7,
        zip_code: 3020,
        population: 4077036,
        rating: 2.38,
        internet: '55 MBPs',
        best_nbh: 'Брансуик',
        photo: 'https://wallscloud.net/img/resize/1024/768/MM/2019-04-14-%D0%90%D0%B2%D1%81%D1%82%D1%80%D0%B0%D0%BB%D0%B8%D1%8F%2C%D0%9C%D0%B5%D0%BB%D1%8C%D0%B1%D1%83%D1%80%D0%BD.jpg ',
        video_url: 'https://www.youtube.com/watch?v=0GXrth_430g&ab_channel=GlobalVillage',
        map_screen: 'https://nomadlist.com/assets/img/static-maps/melbourne-australia.png?1648598492',
        map_url: 'https://goo.gl/maps/XbV2yzagEe67BaVy9',
        nbhs_map: 'https://hoodmaps.com/melbourne-neighborhood-map',
        quality_of_life: '4',
        family_score: '4',
        safety: '3',
        english_speaking: '5',
        nightlife: '3',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Дубай',
        country_id: 8,
        zip_code: 00000,
        population: 2100000,
        rating: 2.84,
        internet: '8 MBPs',
        best_nbh: 'DSO & International city',
        photo: 'https://images.wallpaperscraft.ru/image/single/dubay_zdanie_nebo_krasivyy_peyzazh_arhitektura_850_1024x768.jpg',
        video_url: 'https://www.youtube.com/watch?v=AxFQY6qcOrg',
        map_screen: 'https://nomadlist.com/assets/img/static-maps/dubai-united-arab-emirates.png?1641513841',
        map_url: 'https://www.google.com/maps/@25.2048,55.2708,13z',
        nbhs_map: 'https://hoodmaps.com/dubai-neighborhood-map',
        quality_of_life: '3',
        family_score: '3',
        safety: '5',
        english_speaking: '2',
        nightlife: '2',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Чангу',
        country_id: 10,
        zip_code: 80351,
        population: 30000,
        rating: 4.1,
        internet: '27 MBPs',
        best_nbh: 'Berawa',
        upcoming_nbh: 'Tumbuk Bayuh',
        photo: 'https://mind-flows.com/wp-content/uploads/2022/07/canggu-0-1024x768.jpg',
        video_url: 'https://youtu.be/r2fTNj8L654',
        map_screen: 'https://nomadlist.com/assets/img/static-maps/canggu-bali-indonesia.png?1641513641',
        map_url: 'https://www.google.com/maps/@-8.6531344,115.1317479,13z',
        nbhs_map: 'https://hoodmaps.com/canggu-neighborhood-map',
        quality_of_life: '4',
        family_score: '3',
        safety: '4',
        english_speaking: '3',
        nightlife: '5',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Бангкок',
        country_id: 9,
        zip_code: 10100,
        population: 5800000,
        rating: 3.85,
        internet: '17 MBPs',
        best_nbh: 'Исторический центр',
        upcoming_nbh: 'Huai Kwang',
        photo: 'https://q-cf.bstatic.com/images/hotel/max1024x768/211/211312502.jpg',
        video_url: 'https://youtu.be/n6VQsOvNvyQ',
        map_screen: 'https://nomadlist.com/assets/img/static-maps/bangkok-thailand.png?1660521647',
        map_url: 'https://www.google.com/maps/@13.7566968,100.5019493,13z',
        nbhs_map: 'https://hoodmaps.com/bangkok-neighborhood-map',
        quality_of_life: '4',
        family_score: '3',
        safety: '4',
        english_speaking: '2',
        nightlife: '5',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Пхукет',
        country_id: 9,
        zip_code: 83000,
        population: 91000,
        rating: 3.12,
        internet: '17 MBPs',
        best_nbh: 'Най Харн',
        upcoming_nbh: 'Равай',
        photo: 'https://7d9e88a8-f178-4098-bea5-48d960920605.selcdn.net/72a5b02b-cdaa-463c-8906-4caf9e470e98/-/scale_crop/1024x768/center/-/quality/lighter/',
        video_url: 'https://www.youtube.com/watch?v=c-TPwFt-epw',
        map_screen: 'https://nomadlist.com/assets/img/static-maps/phuket-thailand.png?1654905939',
        map_url: 'https://www.google.com/maps/@7.883306,98.374416,13z',
        nbhs_map: 'https://hoodmaps.com/phuket-neighborhood-map',
        quality_of_life: '4',
        family_score: '4',
        safety: '4',
        english_speaking: '2',
        nightlife: '5',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Стамбул',
        country_id: 1,
        zip_code: 34420,
        population: 15000000,
        rating: 3.47,
        internet: '6 MBPs',
        best_nbh: 'Bebek Park',
        upcoming_nbh: 'Султанахмет Айа София',
        photo: 'https://wikiway.com/upload/hl-photo/c9b/bd9/mechet-suleymanie_79.jpg',
        video_url: 'https://youtu.be/J4u05Qt-4yU',
        map_screen: 'https://nomadlist.com/assets/img/static-maps/phuket-thailand.png?1654905939',
        map_url: 'https://nomadlist.com/assets/img/static-maps/istanbul-turkey.png?1653091253',
        nbhs_map: 'https://hoodmaps.com/istanbul-neighborhood-map',
        quality_of_life: '4',
        family_score: '3',
        safety: '4',
        english_speaking: '2',
        nightlife: '5',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Сities', null, {});
  },
};
