/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Users', [
      {
        login: 'Sasha',
        email: 'sasha69@tudasuda.ua',
        password: '123',
        avatar: 'https://peopletalk.ru/wp-content/uploads/2016/08/116724-4950-1.jpg',
        info: ' Джава скрипт в массы, и натуралам и 3-2-1 ',
        profession: 'Продюсер',
        birth_country: 'Россия',
        current_country: 'Турция',
        future_country: 'Грузия',
        admin: true,
        telegram: 'AlexandrGrebennikov',
        future_city_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Alex',
        email: 'suroviy95r@gmail.com',
        password: '1',
        avatar: 'https://www.film.ru/sites/default/files/people/1455319-938831.jpg',
        info: 'Люблю покер и крутые тачки',
        profession: 'Риелтор (коммерческая недвижимость)',
        birth_country: 'Россия',
        current_country: 'Россия',
        future_country: 'Турция',
        admin: false,
        telegram: 'AlexandrGrebennikov',
        future_city_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Alina',
        email: 'alechkar@gmail.com',
        password: '1',
        avatar: 'https://cdn.ren.tv/cache/960x540/media/img/f3/b4/f3b4e9f604877a3a000ca1339e50109b18270eda.JPG',
        info: 'Пишите - познакомимся!!!',
        profession: 'Модель',
        birth_country: 'Россия',
        current_country: 'Алания',
        future_country: 'Дубай',
        current_city_id: 1,
        future_city_id: 8,
        admin: false,
        telegram: 'lelyarai',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Martin',
        email: 'martin@cat.com',
        password: '1',
        avatar: 'https://static.probusiness.io/720x480c/n/03/d/38097027_439276526579800_2735888197547458560_n.jpg',
        info: ' Люблю животных ',
        profession: 'Айболит',
        birth_country: 'Россия',
        current_country: 'Россия',
        future_country: 'Грузия',
        future_city_id: 2,
        admin: false,
        telegram: 'martincat',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Alice',
        email: 'alice@sexy.com',
        password: '1',
        avatar: 'https://www.svoiludi.ru/images/tb/626/bangkok-1270137101_w990h1000.jpg',
        info: 'Хочу переехать в Бангкок',
        profession: 'Гид',
        birth_country: 'Россия',
        current_country: 'Россия',
        future_country: 'Бангкок',
        future_city_id: 10,
        admin: false,
        telegram: 'BoryaBest',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Masha',
        email: 'masha@mail.ru',
        password: '1',
        avatar: 'https://cdn.trinixy.ru/pics5/20170524/beautiful_girls_26.jpg',
        info: 'Море - моя сихия!',
        profession: 'Актриса театра и кино',
        birth_country: 'Россия',
        current_country: 'Мадейра',
        future_country: 'Алания',
        current_city_id: 6,
        future_city_id: 1,
        admin: false,
        telegram: 'masha123',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Alysa',
        email: 'Alysa91@funny.com',
        password: '1',
        avatar: 'https://www.film.ru/sites/default/files/styles/thumb_260x320/public/persones/_imported/2010431.jpg',
        info: ' Люблю классическую музыку ',
        profession: 'Доктор',
        birth_country: 'Россия',
        current_country: 'Россия',
        future_country: 'Армения',
        admin: false,
        telegram: 'funny',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Borya',
        email: 'BoryaBest@sexy.com',
        password: '1',
        avatar: 'https://www.film.ru/sites/default/files/styles/thumb_260x320/public/people/gregoire-ludig_reference.jpg',
        info: ' Застенчивый , но накаченный молодой человек',
        profession: 'Бодибилдер',
        birth_country: 'Россия',
        current_country: 'Таиланд',
        future_country: 'Лос-Анджелес',
        current_city_id: 9,
        future_city_id: 5,
        admin: false,
        telegram: 'BoryaBest',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Nastya',
        email: 'littleGirl@yashina.com',
        password: '1',
        avatar: 'https://www.film.ru/sites/default/files/styles/thumb_260x320/public/people/1455863-1390864.jpg',
        info: ' Люблю смешные шутки и мальчиков с большими кошельками ',
        profession: 'Модель',
        birth_country: 'Россия',
        current_country: 'Таиланд',
        future_country: 'Грузия',
        current_city_id: 10,
        future_city_id: 2,
        admin: false,
        telegram: 'littleGirl',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Artem',
        email: 'oMyGod@polkovnikov.com',
        password: '1',
        avatar: 'https://cinewest.ru/wp-content/uploads/2014/06/leonardo-di-kaprio-Copy.jpg',
        info: 'Люблю грязный юмор',
        profession: 'Фрилансер',
        birth_country: 'Россия',
        current_country: 'Россия',
        future_country: 'Таиланд',
        future_city_id: 11,
        admin: false,
        telegram: 'polkovnikov93',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Olga',
        email: 'skromnya777@pavlova.com',
        password: '1',
        avatar: 'https://otvet.imgsmail.ru/download/283116618_fda024e88a340a4e4ec27ebca1c60d70_800.jpg',
        info: ' Фанатею от татуировок и мозгов ',
        profession: 'Юрист',
        birth_country: 'Россия',
        current_country: 'Мельбурн',
        future_country: 'Турция',
        future_city_id: 1,
        admin: false,
        telegram: 'skromnya777',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Seva',
        email: 'Pavlenko91@sevochka.com',
        password: '1',
        avatar: 'https://ladybu.ru/wp-content/uploads/2021/05/neverbalnye-priznaki-simpatii-1024x683.jpg',
        info: ' Обычный миллиардер с ангельским личиком ',
        profession: 'Бизнес-тренер',
        birth_country: 'Россия',
        current_country: 'Грузия',
        future_country: 'Таиланд',
        current_city_id: 2,
        future_city_id: 10,
        admin: false,
        telegram: 'Pavlenko91',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Sergey',
        email: 'nikitin@bigpapa.com',
        password: '1',
        avatar: 'https://hi-news.ru/wp-content/uploads/2018/11/SP_ZTE_Selfi_02-750x563.jpg',
        info: ' Мягкий человек, живу с мамой',
        profession: 'Библиотекарь',
        birth_country: 'Россия',
        current_country: 'Турция',
        future_country: 'Австралия',
        current_city_id: 1,
        future_city_id: 7,
        admin: false,
        telegram: 'bigpapa',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Kirill',
        email: 'somova1@kira.com',
        password: '1',
        avatar: 'https://i.pinimg.com/originals/9c/6f/67/9c6f678178563c8bd1448ef18f1970a0.jpg',
        info: ' Люблю готовить и танцевать ',
        profession: 'Стриптезер',
        birth_country: 'Россия',
        current_country: 'Мельбурн',
        future_country: 'Америка',
        current_city_id: 7,
        future_city_id: 5,
        admin: false,
        telegram: 'veryhotMoscow',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Polina',
        email: 'gorbatova@polya.com',
        password: '1',
        avatar: 'https://nevsepic.com.ua/uploads/posts/2011-04/1303553495_olga-kurylenko147_www.nevseoboi.com.ua.jpg',
        info: ' Безумно красивая, но глупая девушка ',
        profession: 'Фриланс',
        birth_country: 'Россия',
        current_country: 'Тбилиси',
        future_country: 'Венгрия',
        current_city_id: 2,
        future_city_id: 4,
        admin: false,
        telegram: 'gorbatova',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'ArtemBar',
        email: 'artbar@gmail.com',
        password: '1',
        avatar: 'https://cdn2.tu-tu.ru/image/pagetree_node_data/2/0ad42704b8fffd99ee94f38d5ed424ad/',
        info: 'Сойки - рулят!',
        profession: 'Full-Stack JS Developer',
        birth_country: 'Россия',
        current_country: 'Грузия',
        future_country: 'Бангкок',
        current_city_id: 2,
        future_city_id: 10,
        admin: false,
        telegram: 'ArtBarinov',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Stepan',
        email: 'rarnov@stepa.com',
        password: '1',
        avatar: 'http://www.rewizor.ru/files/48611izts.jpg',
        info: ' Собираю древние монеты и карточки покемонов ',
        profession: 'Программист',
        birth_country: 'Россия',
        current_country: 'Тбилиси',
        future_country: 'Анталия',
        current_city_id: 2,
        future_city_id: 1,
        admin: false,
        telegram: 'rarnov777',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Nikita',
        email: 'svetlov40@Nik.com',
        password: '1',
        avatar: 'https://i.sunhome.ru/dreamer/151/vozlyublennyiy.xxl.jpg',
        info: ' Люблю аниме ',
        profession: 'Дальнобойщик',
        birth_country: 'Россия',
        current_country: 'Россия',
        future_country: 'Анталия',
        future_city_id: 1,
        admin: false,
        telegram: 'svetlov98',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Tamara',
        email: 'tomchik@stressova.com',
        password: '1',
        avatar: 'https://www.kino-teatr.ru/news/16528/148869.jpg',
        info: ' Увлекаюсь стрельбой из лука ',
        profession: 'балерина',
        birth_country: 'Россия',
        current_country: 'Россия',
        future_country: 'Анталия',
        future_city_id: 1,
        admin: false,
        telegram: 'stressova',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Vera',
        email: 'Vera@panina.com',
        password: '1',
        avatar: 'https://ka-ap.ru/wp-content/uploads/d/3/a/d3a8dcae2767aef0d76100e123c331d4.jpeg',
        info: ' Меня сложно найти и легко потерять ',
        profession: 'Учитель',
        birth_country: 'Россия',
        current_country: 'Тбилиси',
        future_country: 'Таиланд',
        current_city_id: 2,
        future_city_id: 11,
        admin: false,
        telegram: 'verochka',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Filip',
        email: 'Fil@gorodnov.com',
        password: '1',
        avatar: 'https://cinewest.ru/wp-content/uploads/2021/09/gollivudskie-aktery-imena-proiznosim-nepravilno-11-eshton-kutcher.jpg',
        info: ' Люблю выносить мозг любимой ',
        profession: 'Строитель',
        birth_country: 'Россия',
        current_country: 'Анталия',
        future_country: 'Австралия',
        current_city_id: 7,
        future_city_id: 7,
        admin: false,
        telegram: 'perchik',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Elena',
        email: 'egorova@lena.com',
        password: '1',
        avatar: 'http://almode.ru/uploads/posts/2021-03/1617032446_1-p-aktrisa-yelena-podkaminskaya-1.jpg',
        info: ' Люблю собирать пазлы ',
        profession: 'Адвокат',
        birth_country: 'Россия',
        current_country: 'Индонезия',
        future_country: 'США',
        current_city_id: 5,
        future_city_id: 9,
        admin: false,
        telegram: 'egorova',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Denis',
        email: 'denchik@volya.com',
        password: '1',
        avatar: 'https://horrorzone.ru/uploads/1-wallpapers/wallpapers-persons/j/jensen-ackles/jensen-ackles02.jpg',
        info: ' Люблю путешествовать по восточной Европе ',
        profession: 'Дизайнер',
        birth_country: 'Россия',
        current_country: 'Россия',
        future_country: 'Тайланд',
        future_city_id: 11,
        admin: false,
        telegram: 'denchik',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Kate',
        email: 'katenka@error.com',
        password: '1',
        avatar: 'https://mykaleidoscope.ru/uploads/posts/2022-06/1654673955_38-mykaleidoscope-ru-p-kare-na-krupnoe-litso-devushka-krasivo-fot-41.jpg',
        info: ' Увлекаюсь выращиванием цветов на даче ',
        profession: 'медсестра',
        birth_country: 'Россия',
        current_country: 'Таиланд',
        future_country: 'Австралия',
        current_city_id: 10,
        future_city_id: 7,
        admin: false,
        telegram: 'docipoki',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Anton',
        email: 'mcanton@rap21.com',
        password: '1',
        avatar: 'https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-image-fdd61997-462c-4211-b606-8aef28897f6b&mb=webpulse',
        info: 'Жизнь это рэп и я в ней Эминем',
        profession: 'музыкант',
        birth_country: 'Россия',
        current_country: 'Россия',
        future_country: 'Грузия',
        future_city_id: 2,
        admin: false,
        telegram: 'mcanton',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Nona',
        email: 'spasiboZaReact2022@nonchik.com',
        password: '1',
        avatar: 'https://corsairs-bay.ucoz.ru/_fr/3/3569974.jpeg',
        info: ' Изучаю Реакт медленно и с проблемами ',
        profession: 'Повар',
        birth_country: 'Россия',
        current_country: 'Россия',
        future_country: 'Тбилиси',
        future_city_id: 2,
        admin: false,
        telegram: 'nonchik',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Eva',
        email: 'longoria@Eva.com',
        password: '1',
        avatar: 'https://avrorra.com/wp-content/uploads/2019/02/post_5c586f6088802.jpg',
        info: ' Пять раз  была замужем ',
        profession: 'тренер по фигурному катанию',
        birth_country: 'Россия',
        current_country: 'США',
        future_country: 'Тбилиси',
        current_city_id: 5,
        future_city_id: 2,
        admin: false,
        telegram: 'longoriaIce',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'David',
        email: 'davidik@rus.com',
        password: '1',
        avatar: 'https://cdn.intesense.ru/wp-content/uploads/2018/05/2018-05-29_17-56-35_993615.jpg',
        info: ' Покатаю на своем байке ',
        profession: 'Бармен',
        birth_country: 'Россия',
        current_country: 'Россия',
        future_country: 'Тбилиси',
        future_city_id: 2,
        admin: false,
        telegram: 'motoBike',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Tanya',
        email: 'Tanya@pogodkina.com',
        password: '1',
        avatar: 'https://i.pinimg.com/originals/85/57/e4/8557e45e3f7311d2d6994a86dbd6b34b.jpg',
        info: ' Фанат юмора Антона Алексеевича ',
        profession: 'Логист',
        birth_country: 'Россия',
        current_country: 'Россия',
        future_country: 'Бали',
        future_city_id: 9,
        admin: false,
        telegram: 'pogodkina',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Tapac',
        email: 'Tapac@42.com',
        password: '1',
        avatar: 'https://i.pinimg.com/originals/95/1c/59/951c596c51cc2ed9dc0637effa7f0b5a.jpg',
        info: 'Пересматриваю лекции Антона Алексеевича',
        profession: 'Певец',
        birth_country: 'Россия',
        current_country: 'Турция',
        future_country: 'Таиланд',
        current_city_id: 2,
        future_city_id: 10,
        admin: false,
        telegram: 'tapac',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Isa',
        email: 'sila@isa.com',
        password: '1',
        avatar: 'https://www.startfilm.ru/images/base/person/21_03_14/17931_pine_n0qsvrjdju1qhlfm8o1_1280.jpg',
        info: ' Спорт мое все ',
        profession: 'Футболист',
        birth_country: 'Россия',
        current_country: 'Тайланд',
        future_country: 'Тайланд',
        current_city_id: 11,
        future_city_id: 2,
        admin: false,
        telegram: 'sila',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Тanya',
        email: 'tanya@mail.ru',
        password: '123',
        avatar: 'blob:https://web.telegram.org/1f1acc6f-8c82-4022-80ac-1bb7e37fd05e',
        info: 'Мечта - не работать',
        profession: 'Продюсер',
        birth_country: 'Россия',
        current_country: 'Турция',
        future_country: 'Тайланд',
        admin: false,
        telegram: 'brstk',
        current_city_id: 1,
        future_city_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Olya',
        email: 'olyalya@mail.ru',
        password: '123',
        avatar: 'https://klike.net/uploads/posts/2022-08/1659506767_1.jpg',
        info: 'Ищу работу на Бали',
        profession: 'HR',
        birth_country: 'Россия',
        current_country: 'Россия',
        future_country: 'Грузия',
        admin: false,
        telegram: 'lelyarai',
        future_city_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Dimochka',
        email: 'dimon@mail.ru',
        password: '123',
        avatar: 'https://avatarko.ru/img/kartinka/20/zhivotnye_sobaka_ochki_shapka_19742.jpg',
        info: 'Фотографирую людей по бартеру',
        profession: 'Фотограф',
        birth_country: 'Россия',
        current_country: 'Тайланд',
        future_country: 'Алания',
        current_city_id: 1,
        future_city_id: 9,
        admin: false,
        telegram: 'dmitriipinchuk',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        login: 'Lesha',
        email: 'pilpan@cat.com',
        password: '1',
        avatar: 'https://s13.stc.yc.kpcdn.net/share/i/instagram/B44solahwlo/wr-1280.webp',
        info: 'Крутой перец',
        profession: 'Айболит',
        birth_country: 'Россия',
        current_country: 'Россия',
        future_country: 'Грузия',
        future_city_id: 2,
        admin: false,
        telegram: 'pilpan',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },
  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Users', null, {});
  },
};
