/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Costs', [
      {
        city_id: 1,
        cost_living: 1773,
        hotel: 892,
        apartment: 406,
        beer: 1.08,
        cappuccino: 1.51,
        dinner: 11,
        petrol: 1.27,
        kindergarten: 169.17,
        salary: 304.61,
        coworking: 252,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_id: 2,
        cost_living: 1931,
        hotel: 702,
        apartment: 441,
        beer: 1.41,
        cappuccino: 2.41,
        dinner: 8.83,
        petrol: 1.36,
        kindergarten: 208.48,
        salary: 448.92,
        coworking: 254,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_id: 3,
        cost_living: 1556,
        hotel: 545,
        apartment: 326,
        beer: 2.6,
        cappuccino: 0.66,
        dinner: 3.98,
        petrol: 1.58,
        kindergarten: 312,
        salary: 787,
        coworking: 239,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_id: 4,
        cost_living: 1988,
        hotel: 1053,
        apartment: 548,
        beer: 3.17,
        cappuccino: 0.77,
        dinner: 6.77,
        petrol: 1.32,
        kindergarten: 311,
        salary: 1075,
        coworking: 166,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_id: 5,
        cost_living: 5160,
        hotel: 3700,
        apartment: 1940,
        beer: 6.03,
        cappuccino: 5,
        dinner: 17,
        petrol: 1.60,
        kindergarten: 1361,
        salary: 4817,
        coworking: 298,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_id: 6,
        cost_living: 2076,
        hotel: 837,
        apartment: 588,
        beer: 3.43,
        cappuccino: 2.28,
        dinner: 6.86,
        petrol: 1.99,
        kindergarten: 220,
        salary: 1646,
        coworking: 78,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_id: 7,
        cost_living: 4862,
        hotel: 1331,
        apartment: 2702,
        beer: 5.61,
        cappuccino: 3.20,
        dinner: 22,
        petrol: 1.31,
        kindergarten: 1561,
        salary: 4506,
        coworking: 352,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_id: 8,
        cost_living: 4900,
        hotel: 1724,
        apartment: 1988,
        beer: 5.23,
        cappuccino: 2.27,
        dinner: 19,
        petrol: 1.15,
        kindergarten: 731,
        salary: 3135,
        coworking: 150,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_id: 9,
        cost_living: 1892,
        hotel: 507,
        apartment: 1266,
        beer: 2.53,
        cappuccino: 0.98,
        dinner: 2.73,
        petrol: 0.81,
        kindergarten: 95,
        salary: 298,
        coworking: 224,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_id: 10,
        cost_living: 1890,
        hotel: 412,
        apartment: 1167,
        beer: 2.89,
        cappuccino: 2.38,
        dinner: 6.7,
        petrol: 1.12,
        kindergarten: 470,
        salary: 550,
        coworking: 180,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_id: 11,
        cost_living: 2605,
        hotel: 379,
        apartment: 888,
        beer: 2.75,
        cappuccino: 2.20,
        dinner: 13,
        petrol: 1.17,
        kindergarten: 396,
        salary: 493,
        coworking: 427,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Costs', null, {});
  },
};
